* Here we systematically derive some basic facts of discrete-time Markov processes. For simplicity, we will restrict ourselves to finite state spaces and finite time so as to keep the exposition elementary.
* Let $S$ denote the state space, which, for now, will be a finite set.  Define the set of $n$-step histories as $H_{n} = \mathsf{Map}(\{0, 1, 2, \ldots n\}, S)$.  I.e. a history is a sequence of states labelled by times.  We may visualize a history as a path in the state space.  Optionally, we might endow $S$ with the structure of a graph and only allow paths which lie in the graph as histories.
* A _stochastic process_ is a probability distribution $P \in \mathcal{D}(H_n)$ on histories.  Two important quantities associated to such a process are:
:PROPERTIES:
:END:
** The probability of being in a found in a state $q$ at a time $t$:
$$p(q,t) = P(\{h \in H_{n} \mid h(t) = q\})$$
** The probability of making a transition from state $q$ at time $t$ to state $q'$ at (a later) time $t$:
$$T(q', t' \mid q,t) = P(\{h \in H_{n} \mid h(t') = q'\} \mid \{h \in H_{n} \mid h(t) = q\})$$
* We now assume that the process is _one-step Markovian_, a.k.a. _memoryless_.  This means that future values only depend upon the present value and not on past values.  Formally, given any times $0 < t_1 < t_2 < t_3 < n$ and any values $q_1, q_2, q_3 \in S$, we have
$$\begin{aligned} &P (\{h \in H_{n} \mid h(t_3) = q_3\} \mid \{h \in H_{n} \mid h(t_2) = q_2\}) = \\ &P (\{h \in H_{n} \mid h(t_3) = q_3\} \mid \{h \in H_{n} \mid h(t_2) = q_2 \land h(t_1) = q_1\}) \end{aligned}$$
* Next, we derive an important identity for Markov processes.  We begin with a general observation about conditional probabilities.  Suppose that a family of events $B_{i}$ indexed by some set $I$ partition the sample space.  Then given events $A$ and $C$, we have
$$\begin{aligned}\sum_{i \in I} P(A \mid B_{i} \cap C) P (B_{i} | C) &= \sum_{i \in I} \frac{P(A \cap B_{i} \cap C)}{P(B \cap C)} \frac{P(B_{i} \cap C)}{P(C)} \\ &= \frac{1}{P(C)} \sum_{i \in I} P(A \cap B_{i} \cap C) \\ &= \frac{P(A \cap C)}{P(C)} \\ &= P(A \mid C)\end{aligned} $$
Now make the choices
$$\begin{aligned} I &= S \\ A &=  \\ B_\{h \in H_{n} \mid h(t) = q'\}{i} &= \\ C &= \end{aligned}$$