#+TITLE: Intrinsic and Extrinsic Thermodynamics for Stochastic Population Processes with Multi-Level Large-Deviation Structure by Eric Smith in 2020

** citation
*** E. Smith, “Intrinsic and Extrinsic Thermodynamics for Stochastic Population Processes with Multi-Level Large-Deviation Structure,” Entropy, vol. 22, no. 10, p. 1137, Oct. 2020
** Contents
*** I. INTRODUCTION
***** II. MULTI-LEVEL SYSTEMS
****** 1. Micro to macro, within and between levels
****** A. Models based on population processes
****** B. Stochastic description within the mesoscale
****** C. System-environment decompositions of the entropy change
******* 1. The information/heat decomposition of total relative-entropy change
******* 2. Relative entropy referencing the system steady state at instantaneous parameters
***** III. HAMILTON-JACOBI THEORY FOR LARGE DEVIATIONS
****** A. Generating functions, Liouville equation, and the Hamilton-Jacobi construction for saddle points
****** B. The stationary distribution and macrostates
***** IV. POPULATION PROCESSES WITH CRN-FORM GENERATORS
****** A. Hypergraph generator of state-space transitions
Comparing with the "moment hierarchy" paper clarifies the notation.
******* 1. Descaling of transition matrices for microstates
******* 2. Descaling of transition matrices for macrostates
******* 3. Equations of motion and the \(\mathcal{L} = 0\) manifold
******* 4. The Schlögl cubic model to illustrate
****** B. Large-deviation and Lyapunov roles of the effective action
The
***** V. CYCLE DECOMPOSITIONS AND NON-DECREASE OF INTRINSIC AND EXTRINSIC RELATIVE ENTROPIES
****** A. Complexity classes and cycle decompositions of stationary currents on the hypergraph
****** B. Cycle decomposition in the microstate space, and non-decrease of relative entropy components
***** VI. EXAMPLES
****** A. Dualizing the housekeeping embedding thermodynamics
****** B. Metastability and \(\bar{\rho}^{s}\) as the reference measure for relative entropy
***** VII. DISCUSSION
***** VIII. CONCLUDING REMARKS
