#+TITLE: Journal Club Journal

** This page is meant as as a sort of journal for keeping track of our progress in journal club activities studying literature related to theoretical biology and adjacent subjects.
** Main works --- These are the works we are studying in detail to understand ideas and techniques which we hope to build upon and make use of in our work.
*** NOW [[Intrinsic and Extrinsic Thermodynamics for Stochastic Population Processes with Multi-Level Large-Deviation Structure by Eric Smith in 2020]]
:PROPERTIES:
:now: 1613234567058
:END:
*** Hufton, P. G., Lin, Y. T., & Galla, T. (2019). Classical stochastic systems with fast-switching environments: Reduced master equations, their interpretation, and limits of validity. Physical Review E, 99(3), 032121. https://doi.org/10.1103/PhysRevE.99.032121
***
** Auxiliary literature  --- Along the way, we read other works which provide backround, explain concepts, illustrate by example, and fill in details on topics discussed in the main works.
*** Schnakenberg, J. (1976). Network theory of microscopic and macroscopic behavior of master equation systems. Reviews of Modern Physics, 48(4), 571–585. https://doi.org/10.1103/RevModPhys.48.571
***
