#+TITLE: Method of Characteristics

** Here we will describe the method of characteristics for solving first-order partial differential equations.  We will start simple and gradually build in generality by reducing more complicated equations to simpler equations which we have already solved
** Homogeneous Linear Equations
:PROPERTIES:
:now: 1615330639112
:later: 1615330638397
:END:
*** Theory
:PROPERTIES:
:now: 1616193496303
:later: 1616193492802
:END:

 We begin with the linear differential equation of first order.  Since we are working locally, suppose that \(D\) is an open subset of \(\mathbb{R}^{n}\) and that functions \(a_{1}, \ldots, a_{n} \colon D \to \mathbb{R}\) have been specified.  (So as not to have to think too hard about such matters, let's assume that all functions are infinitely differentiable.)  We consider the differential equation
$$\sum_{i=1}^{n} a_{i} (q) \frac{\partial \phi (q)}{\partial q_{i}} = 0 .$$
We also introduce an initial value surface \(S \subset D\) of codimension 1.  Given a  function \(\phi_{0} \colon S \to \mathbb{R}\), we look for a \(\phi \colon D \to \mathbb{R}\) which satisfies the differential equation such that the restriction of \(\phi\) to \(S\) equals \(\phi_0\).  Later on, we will find conditions on the initial data which allow us to find a unique local solution to the initial value problem.

Now consider the system of ordinary differential equations (a.k.a. dynamical system)
$$\frac{df_i (t)}{dt} = a_{i} (f(t))$$
for \(f \colon I \to \mathbb{R}\) where \(I \subset \mathbb{R}\) is some interval. Geometrically, these describe the flow generated by the vector field on \(D\) whose components are the \(a_{i}\).  Given a solution of these equations, the chain rule tells us that
$$\frac{d \phi(f(t))}{dt} = \sum_{i=1}^{n} a_{i} (t) \left[ \frac{\partial \phi(q)}{\partial q_{i}} \right]_{q_{i}= f_i (t)}$$
so we have
$$\left[\sum_{i=1}^{n} a_{i} (q) \frac{\partial \phi (q)}{\partial q_{i}}\right]_{q_{i}= f_i (t)} = \frac{d \phi(f(t))}{dt}$$
Thus, if \(\phi\) is a solution of the partial differential equation and \(f\) is a solution to the ordinary differential equations, then \(\phi \circ f\) is constant.  Conversely, if \(\phi \circ f\) is constant, then \(\phi\) satisfies the partial differential equation on the image of \(f\).

We can use these observations to solve the initial value problem locally.  Suppose that the vector field \(a_{i}\) is nowhere tangent to the initial value surface \(S\).  Then, given any point \(x \in S\), there is some interval \([-\epsilon, \epsilon]\) and some \(f  \colon [-\epsilon, \epsilon] \to D\) which satisfies the differential equation with initial condition \(f(0) = x\), and, furthermore, the curve parameterized by \(f\) intersects \(S\) transversely at \(x\) but does not intersect \(S\) in any point other than \(x\).

Making use of regular dependence of the solution of the differential equation on initial data, we can assert more.  Namely, we there exists some open subset \(S' \subseteq S\) such that \(x \in S'\) and a family of functions \(f \times S' \times [-\epsilon, \epsilon] \to D\) indexed by \(S'\) which satisfy the following conditions:
1. For all \(y \in S'\) we have \(f(y, 0) = y\).
2. For all \(y \in S'\), the function \(t \mapsto f(y,t)\) satisfies the ODE.
3. \(f\) maps \(S' \times [-\epsilon, \epsilon]\) isomorphically to some open subset \(D'\) of \(D\).
Then there exists a unique function \(g \colon D' \to S'\) such that \(g(f(x,t)) = x\) for all \(x \in S'\).  (We can take \(g = \mathrm{pr}_{1} \circ f^{-1}\) where \(\mathrm{pr}_{1}\) denotes the canonical mapping of the product onto the first factor.)  Set \(\phi = \phi_0 \circ g\).  From this definition, it follows that the map \(t \mapsto \phi(f(x,t))\) is constant for all \(x\).  By the conclusion we reached earlier, this means that \(\phi\) satisfies the partial differential equation on the image of \(f\) but, by condition 3 above, the image of \(f\) is \(D'\).  By construction, if \(x \in S'\) then \(\phi(x) = \phi_{0} (x)\).  Hence, \(\phi\) solves the initial value problem.
*** Technique
:PROPERTIES:
:later: 1616204027302
:END:



We may summarize what we have done as the following prescription for solving the partial differential equation
$$\sum_{i=1}^{n} a_{i} (q) \frac{\partial \phi (q)}{\partial q_{i}} = 0$$
with initial value data \(\phi(x) = \phi_{0} (x)\) when \(x \in S\).
+ Form the system of ordinary differential equations
$$\frac{df_i (x, t)}{dt} = a_{i} (f(x, t))$$
+ Solve these with initial condition \(f(x,0) = x\) for \(x \in S\).
+ Obtain \(g\) by solving the algebraic equation \(g(f(x,t))= x\).
+ The solution to the initial value problem is \(\phi = \phi_{0} \circ g\).
*** Example

To illustrate, let us solve the equation
$$y \frac{\partial \phi(x,y)}{\partial x} + x \frac{\partial \phi(x,y)}{\partial y} = 0$$
subject to the initial condition \(\phi(x,0) = x^{2}\).  Here the initial value manifold consists of the positive \(x\) axis in \((x,y)\)-space.  The characteristic differential equations are
$$\begin{aligned} \frac{df_{1} (t)}{dt} &= f_{2} (t) \\ \frac{df_{2} (t)}{dt} &= f_{1} (t) \end{aligned}.$$
Any function \(f\) satisfying these equations can be written as
$$f(t) = (c_{1} e^{t} + c_{2} e^{-t}, c_{1} e^{t} - c_{2} e^{-t})$$
for some choice of the constants \(c_{1}\) and \(c_{2}\). Hence, the family of solutions for which we are looking can be expressed as
$$f(x,t) = (k_{1}(x) e^{t} + k_{2}(x) e^{-t}, k_{1}(x) e^{t} - k_{2}(x) e^{-t})$$
where \(k_{1}\) and \(k_{2}\) have been chosen so as to satisfy the initial condition \(f(x,0) = (x,0)\).  This gives us the equations
$$\begin{aligned} k_{1}(x) + k_{2}(x) &= x \\ k_{1}(x) - k_{2}(x) &= 0,\end{aligned}$$
which have the solution
$$\begin{aligned} k_{1}(x) &= \frac{x}{2} \\ k_{2}(x) &= \frac{x}{2},\end{aligned}.$$
Substituting into the general solution of the differential equation, we find that
$$f(x,t) = (x \cosh (t), x \sinh (t)).$$
On account of the trigonometric identity \(\cosh (t)^{2} - \sinh (t)^{2} = 1\), we see that \(g(x,y) = \sqrt{x^{2} - y^{2}}\) satisfies the equation \(g(f(x,t)) = x\).  Note that, in our problem, \(\phi_{0} (x) = x^2\), so we have
$$\phi(x,y) = \phi_{0} (g(x,y)) = x^{2} - y^{2}.$$
Differentiating, substituting, and cancelling, we may confirm that this is a solution of the equation with the correct initial conditions.
** Quasi-linear equations

By introducing more independent variables, we can generalize our result to inhomogeneous and quasi-linear equations.

To solve the inhomogeneous linear equation
$$\sum_{i=1}^n a_i (q) \frac{\partial \phi(q)}{\partial q_i} + b(q) = 0,$$
consider the homogeneous equation
\[\sum_{i=1}^n a_i (q) \frac{\partial \varphi(q,s)}{\partial q_i} + b(q) \frac{\partial \varphi(q,s)}{\partial s}= 0.\]
If we have a solution of the latter equation of the form \(\varphi(q,s) = \phi(q) + s\), then \(\phi\) will satisfy the former equation.

 Next we turn out attention to the quasi-linear equation 
$$\sum_{i=1}^{n} a_{i} (\phi (q), q) \frac{\partial \phi (q)}{\partial q_{i}} = 0.$$
By the chain rule, we have
 $$\frac {\partial}{\partial q_{i}} \chi (\phi(q), q) = \left[\frac{\partial \chi(u,q)}{\partial u} \frac{\partial \phi (q)}{\partial q_{i}} + \frac{\partial \chi (u,q)}{\partial q_{i}}\right]_{u = \phi(q)} .$$
If \[\chi (\phi(q), q)\] is constant, the left-hand side equals zero.  Making this assumption, multiplying by \[a_{i}\] and rearranging, we obtain
$$\left[\frac{\partial \chi(u,q)}{\partial u} \right]_{u = \phi(q)} \sum_{i} a_{i} (\phi(q),q) \frac{\partial \phi (q)}{\partial q_{i}} = -\left[\sum_{i} a_{i} (u,q) \frac{\partial \chi (u,q)}{\partial q_{i}}\right]_{u = \phi(q)}$$
Thus, if  \(\chi\) is a solution of the linear equation \(\sum_{i} a_{i} (u,q) \frac{\partial \chi (u,q)}{\partial q_{i}} = 0\) and we take $\phi$ to be a solution of the equation
$\chi (\phi(q), q) = C$ for some constant $C$, then \(\phi\) is a solution of the quasilinear equation.
*** Technique 

We may summarize what we have done as the following prescription for solving the partial differential equation
$$\sum_{i=1}^n a_i (q) \sum_{i=1}^{n} a_{i} (\phi (q), q) \frac{\partial \phi (q)}{\partial q_{i}} + b(\phi(q), q) = 0$$
with initial value data \(\phi(x) = \phi_{0} (x)\) when \(x \in S\). 
+ Form the system of ordinary differential equations
$$\begin{aligned}\frac{df_i (x, t)}{dt} &= a_{i} (h(x, t), f(x, t)) \\ \frac{dh (x, t)}{dt} &= b (h(x, t), f(x, t))\end{aligned}$$ 
+ Solve these with initial conditions \(f(x,0) = x\) and \(h(x,0) = \phi_{0} (x)\) for \(x \in S\). 
+ Obtain \(g\) by solving the algebraic equations \(g(f(x,t))= x\) and \(k(f(x,t))= t\).
+ The solution to the initial value problem is given as \(\phi(x) = h(g(x), k(x))\).
*** Example
$$\frac{\partial u(x,t)}{\partial t} - u(x,t) \frac{\partial u(x,t)}{\partial x} = x^2$$
** Non-linear equations
:PROPERTIES:
:later: 1615001623629
:END:


Now we generalize to non-linear equations of the form
\[ H\left( \frac{\partial}{\partial q_{\cdot}} \phi(q), q_{\cdot} \right) = 0.\]
To reduce such an equation to a quasilinear equation, we introduce new variables \(p_{i}\) and equations \(p_{i} = \frac{\partial \phi}{\partial q_{i}}\).  Taking the derivative of the original equation and substituting, we find that
\[ \sum_{i} \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial p_i} \frac{\partial p_i}{\partial q_{j}} + \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial q_{j}} = 0\]
Differentiating the new equations, we obtain the integrability conditions
\[\frac{\partial p_{i}}{\partial q_{j}} =  \frac{\partial p_{j}}{\partial q_{i}}.\]
Combining, we obtain the equations
\[ \sum_{i} \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial p_i} \frac{\partial p_j}{\partial q_{i}} + \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial q_{j}} = 0\]

The equations we have just derived are quasi-linear.  Furthermore, we note that, locally, solutions of this new system are equivalent to solutions of the original equation.  Suppose that \(p_{i} = f_{i} (q_{\cdot})\) is a solution to the system.  Because the integrability conditions are satisfied, we can locally find \(\phi\) such that \(p_{i} = \partial \phi / \partial q_{i}\).  Substituting back, we find that
\[\frac{\partial}{\partial j} H \left(\frac{\partial \phi}{\partial q_{\cdot}}, q_{\cdot}\right) = 0,\]
hence
\[ H\left( \frac{\partial \phi}{\partial q_{\cdot}}, q_{\cdot} \right) = c\]
for some constant \(c\).  If we know that \(c = 0\) at some point (e.g. from initial conditions) then \(c = 0\) everywhere, so the original equation is satisfled.
*** Technique
*** Example
** References
*** [[https://lccn.loc.gov/96022069][Forsyth, Andrew Russell. A treatise on differential equations. Dover Publications, 1996.]]
*** [[https://lccn.loc.gov/89112829][Courant, Richard, and David Hilbert. Methods of Mathematical Physics: Partial Differential Equations. John Wiley & Sons, 2008.]]
*** [[https://lccn.loc.gov/a56004187][Duff, G.F.D. Partial Differential Equations.  U, Toronto Press, 1956]]
*** [[https://lccn.loc.gov/91058716][Zwillinger, Daniel. Handbook of differential equations. Boston : Academic Press, 1992.]]