#+TITLE: Method of Characteristics

** Here we will describe the method of characteristics for solving first-order partial differential equations.  We will start simple and gradually build in generality by reducing more complicated equations to simpler equations which we have already solved
** Linear equations
:PROPERTIES:
:now: 1615330639112
:later: 1615330638397
:END:
*** Theory

 We begin with the linear differential equation of first order.  Since we working locally, suppose that \(D\) is and open subset of \(\mathbb{R}^{n}\) and that functions \(a_{i},b,c \colon D \to \mathbb{R}\) have been specified.  (So as not to have to think too hard about such matters, let's assume that all functions are infinitely differentiable.)  We consider the differential equation
\[\sum_{i=1}^{n} a_{i} (q) \frac{\partial \phi (q)}{\partial q_{i}} + b(q) \phi (q) + c(q) = 0 .\]
We also introduce an initial value surface \(S \subset D\) of codimension 1.  Given a  function \(\phi_{0} \colon S \to \mathbb{R}\), we look for a \(\phi \colon D \to \mathbb{R}\) which satisfies the differential equation such that the restriction of \(\phi\) to \(S\) equals \(\phi_0\).  Later on, we will find technical conditions on the initial data which allow us to find a unique local solution to the initial value problem.

Now consider the system of ordinary differential equations (a.k.a. dynamical system)
\[\frac{df_i (t)}{dt} = a_{i} (f(t))\]
for \(f \colon I \to \mathbb{R}\) where \(I \subset \mathbb{R}\) is some interval. Geometrically, these describe the flow generated by the vector field on \(D\) whose components are the \(a_{i}\).  Given a solution of these equations, the chain rule tells us that
\[\frac{d \phi(f(t))}{dt} = \sum_{i=1}^{n} a_{i} (t) [\frac{\partial \phi(q)}{\partial q_{i}} ]_{q_{i}= f_i (t)}\]
so we have
\[[\sum_{i=1}^{n} a_{i} (q) \frac{\partial \phi (q)}{\partial q_{i}} + b(q) \phi (q) + c(q)]_{q_{i}= f_i (t)} = \frac{d \phi(f(t))}{dt} + b(f(t)) \phi(f(t)) + c(f(t))\]
Thus, if we solve the differential equation
\[\frac{dg(t)}{dt} + b(f(t)) g(t) + c(f(t)) = 0 \]
for \(g\), we can construct a solution to the original partial differential equation from the solutions to the ordinary differential equations by solving the algebraic equation \(\phi(f(t)) = g(t)\).

In more detail, this final step in the solution goes as follows.  Suppose that the vector field \(a_{i}\) is nowhere tangent to the initial value surface \(S\).  Then, given any point \(x \in S\), there is some interval \([-\epsilon, \epsilon]\) and some \(f  \colon [-\epsilon, \epsilon] \to D\) which satisfies the differential equation with initial condition \(f(0) = x\), and, furthermore, the curve parameterized by \(f\) intersects \(S\) transversely at \(x\) but does not intersect \(S\) in any point other than \(x\).

Making use of dependence of the solution of the differential equation on initial data, we can assert more.  Namely, we there exists some \(U\) such that \(x \in U \subseteq S\) and \(f \colon U \times [-\epsilon, \epsilon] \to D\) which satisfy the following conditions:
+ For all \(y \in U\) we have \(f(y, 0) = y\).
+ For all \(y \in U\), the function \(t \mapsto f(y,t)\) satisfies the ODE.
+ \(f\) maps \(U \times [-\epsilon, \epsilon]\) isomorphically to some open subset \(D'\) of \(D\).
*** Technique
*** Example
** Quasi-linear equations

By introducing more independant variables, we can generalize our result to inhomogeneous and quasi-linear equations.

To solve the inhomogeneous linear equation
\[\sum_{i=1}^n a_i (q) \frac{\partial \phi(q)}{\partial q_i} + b(q) = 0,\]
consider the homogeneous equation
\[\sum_{i=1}^n a_i (q) \frac{\partial \varphi(q,s)}{\partial q_i} + b(q) = 0.\]
If we have a solution of the latter equation of the form \(\varp[]\)

 By the chain rule, we have
 \[\frac {\partial}{\partial q_{i}} \chi (\phi(q), q) = \left[\frac{\partial \chi(u,q)}{\partial u} \frac{\partial \phi (q)}{\partial q_{i}} + \frac{\partial \chi (u,q)}{\partial q_{i}}\right]_{u = \phi(q)} .\]
If \[\chi (\phi(q), q)\] is constant, the left-hand side equals zero.  Making this assumption and multiplying by \[a_{i}\] and rearranging, we obtain
\[\left[\frac{\partial \chi(u,q)}{\partial u} \right]_{u = \phi(q)} \sum_{i} a_{i} (\phi(q),q) \frac{\partial \phi (q)}{\partial q_{i}} = -\left[\sum_{i} a_{i} (u,q) \frac{\partial \chi (u,q)}{\partial q_{i}}\right]_{u = \phi(q)}\]
Thus, if  \(\chi\) is a solution of the linear equation \(\sum_{i} a_{i} (u,q) \frac{\partial \chi (u,q)}{\partial q_{i}} = 0\), then \(\phi\) is a solution of the quasilinear equation
** Non-linear equations
:PROPERTIES:
:later: 1615001623629
:END:

Now we generalize to non-linear equations of the form
\[ H\left( \frac{\partial}{\partial q_{\cdot}} \phi(q), q_{\cdot} \right) = 0.\]
To reduce such an equation to a quasilinear equation, we introduce new variables \(p_{i}\) and equations \(p_{i} = \frac{\partial \phi}{\partial q_{i}}\).  Taking the derivative of the original equation and substituting, we find that
\[ \sum_{i} \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial p_i} \frac{\partial p_i}{\partial q_{j}} + \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial q_{j}} = 0\]
Differentiating the new equations, we obtain the integrability conditions
\[\frac{\partial p_{i}}{\partial q_{j}} =  \frac{\partial p_{j}}{\partial q_{i}}.\]
Combining, we obtain the equations
\[ \sum_{i} \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial p_i} \frac{\partial p_j}{\partial q_{i}} + \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial q_{j}} = 0\]

The equations we have just derived are quasi-linear.  Furthermore, we note that, locally, solutions of this new system are equivalent to solutions of the original equation.  Suppose that \(p_{i} = f_{i} (q_{\cdot})\) is a solution to the system.  Because the integrability conditions are satisfied, we can locally find \(\phi\) such that \(p_{i} = \partial \phi / \partial q_{i}\).  Substituting back, we find that
\[\frac{\partial}{\partial j} H \left(\frac{\partial \phi}{\partial q_{\cdot}}, q_{\cdot}\right) = 0,\]
hence
\[ H\left( \frac{\partial \phi}{\partial q_{\cdot}}, q_{\cdot} \right) = c\]
for some constant \(c\).  If we know that \(c = 0\) at some point (e.g. from initial conditions) then \(c = 0\) everywhere, so the original equation is satisfled.
** References
*** [[https://lccn.loc.gov/96022069][Forsyth, Andrew Russell. A treatise on differential equations. Dover Publications, 1996.]]
*** [[https://lccn.loc.gov/89112829][Courant, Richard, and David Hilbert. Methods of Mathematical Physics: Partial Differential Equations. John Wiley & Sons, 2008.]]
*** [[https://lccn.loc.gov/a56004187][Duff, G.F.D. Partial Differential Equations.  U, Toronto Press, 1956]]
*** [[https://lccn.loc.gov/91058716][Zwillinger, Daniel. Handbook of differential equations. Boston : Academic Press, 1992.]]
