#+TITLE: Method of Characteristics

** Here we will describe the method of charactericstics for solving first-order partial differential equations.  We will start simple and gradually build in generality by reducing more complicated equations to simpler equations which we have already solved
** Linear equations
:PROPERTIES:
:later: 1615242889246
:END:

We begin with the linear differential equation of first order.  Since we working locally, suppose that \(D\) is and open subset of \(\mathbb{R}^{n}\) and that functions \(a_{i},b,c \colon D \to \mathbb{R}\) have been specified.  We consider the differential equation
\[\sum_{i=1}^{n} a_{i} (q) \frac{\partial \phi (q)}{\partial q_{i}} + b(q) \phi (q) + c(q) = 0 .\]
We also introduce an initial value surface \(S \subset D\) of codimension 1.  Given a  function \(\phi_{0} \colon S \to \mathbb{R}\), we look for a \(\phi \colon D \to \mathbb{R}\) which satisfies the differential equation such that the restriction of \(\phi\) to \(S\) equals \(\phi_0\).

Now consider the system of ordinary differential equations (a.k.a. dynamical system)
\[\frac{df_i (t)}{dt} = a_{i} (f(t))\]
Geometrically, these describe the flow generated by the vector field on \(D\) whose components are the \(a_{i}\).  Given a solution of these equations, the chain rule tells us that
\[\]
** Quasi-linear equations
** Non-linear equations
:PROPERTIES:
:later: 1615001623629
:END:

Now we generalize to non-linear equations of the form
\[ H\left( \frac{\partial}{\partial q_{\cdot}} \phi(q), q_{\cdot} \right) = 0.\]
To reduce such an equation to a quasilinear equation, we introduce new variables \(p_{i}\) and equations \(p_{i} = \frac{\partial \phi}{\partial q_{i}}\).  Taking the derivative of the original equation and substituting, we find that
\[ \sum_{i} \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial p_i} \frac{\partial p_i}{\partial q_{j}} + \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial q_{j}} = 0\]
Differentiating the new equations, we obtain the integrability conditions
\[\frac{\partial p_{i}}{\partial q_{j}} =  \frac{\partial p_{j}}{\partial q_{i}}.\]
Combining, we obtain the equations
\[ \sum_{i} \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial p_i} \frac{\partial p_j}{\partial q_{i}} + \frac{\partial H(p_{\cdot}, q_{\cdot})}{\partial q_{j}} = 0\]

The equations we have just derived are quasi-linear.  Furthermore, we note that, locally, solutions of this new system are equivalent to solutions of the original equation.  Suppose that \(p_{i} = f_{i} (q_{\cdot})\) is a solution to the system.  Because the integrability conditions are satisfied, we can locally find \(\phi\) such that \(p_{i} = \partial \phi / \partial q_{i}\).  Substituting back, we find that
\[\frac{\partial}{\partial j} H \left(\frac{\partial \phi}{\partial q_{\cdot}}, q_{\cdot}\right) = 0,\]
hence
\[ H\left( \frac{\partial \phi}{\partial q_{\cdot}}, q_{\cdot} \right) = c\]
for some constant \(c\).  If we know that \(c = 0\) at some point (e.g. from initial conditions) then \(c = 0\) everywhere, so the original equation is satisfled.
