#+TITLE: Notation for Probability

** Here we will describe a unified notation for probability based on first principles.  Since this notation is quite sparse --- it uses only two primitive operations, \(\mathcal{D}\) and \(\mathbb{E}\) --- in actual practice, one will likely want to augment it with further symbols, abbreviations and "syntactic sugar".  The main purpose of this exercise is to be able to express things in a consistent way and provide a common ground for defining and comparing statements written in different local dialects.  For simplicity, we will assume that our sets are finite, but one can extend the notation to more advanced situations by taking into account considerations of convergence and measure.
** As a starting point, we have a sample space \(X = (S, E)\), where \(S\) is a set and \(E\) is a Boolean lattice of subsets of \(S\) --- when \(S\) is finite, \(S = 2^S\), the powerset lattice.  One often calls elements of \(S\) outcomes and calls elements of \(E\) events.  We will build up structure by introducing classes of functions.
** Given two sample spaces \(X = (S_X, E_X)\) and \(Y = (S_Y, E_Y)\) a morphism \(m \colon X \to Y\) is specified as \(m = \(D, f)\) where:  \(D \in E_X\) is a subset of and \(f \colon D \to S_Y\) is measurable, i.e. for all \(e \in E_Y\), we have \(f)(of course, in the finite case, any \(f\) will be measurable).
