#+TITLE: Notation for Probability

** Here we will describe a unified notation for probability based on first principles.  Since this notation is quite sparse --- it uses only two primitive operations, \(\mathcal{D}\) and \(\mathbb{E}\) --- in actual practice, one will likely want to augment it with further symbols, abbreviations and "syntactic sugar".  The main purpose of this exercise is to be able to express things in a consistent way and provide a common ground for defining and comparing statements written in different local dialects.  For simplicity, we will assume that our sets are finite, but one can extend the notation to more advanced situations by taking into account considerations of convergence and measure.
** As a starting point, we have a sample space \(X = (S, E)\), where \(S\) is a set and \(E\) is a Boolean lattice of subsets of \(S\) --- when \(S\) is finite, \(S = 2^S\), the powerset lattice.  One often calls elements of \(S\) outcomes and calls elements of \(E\) events.  We will build up structure by introducing classes of functions.
** Given two sample spaces \(X = (S_X, E_X)\) and \(Y = (S_Y, E_Y)\) a morphism \(m \colon X \to Y\) is specified as \(m = (D, f)\) where:  \(D \in E_X\) is a subset of \(S_X\) and the function \(f \colon D \to S_Y\) is measurable, i.e. for all \(e \in E_Y\), we have \(f^{-1} (e) \in S_{X}\) (of course, in the finite case, any \(f\) will be measurable).  Since the composition of two such morphisms is again a morphism, this defines a category \(\mathsf{PProb}\) of probability spaces.  (The first "\(\mathsf{P}\)" stands for "partial".)
** One way which these morphisms usually appear is under the guise of random variables.  Given a sample space of interest, we may define random variables as morphisms from our sample space to some other sample spaces.  Often the target space is taken to be some standard space such as the two-element set or the real line.  Given enough such mappings, we may specify any outcome in our space by the values of these variables and specify any event by specifying a relation between the variables.  This usage is analogous to coordinates in geometry.
** Given a sample space \(X = (S, E)\), we define a probability distribution as a map \(d \colon E \to [0,1] \subset \mathbb{R}\) which satisfies the usual axioms:
:PROPERTIES:
:now: 1611781901176
:later: 1611776710177
:done: 1611776616676
:END:
+ \(d(\emptyset) = 0\)
+ \(d(S) = 1\)
+ \(d(x) + d(y) = d(x \cup y) + d(x \cap y)\)
** (In the infinite case, we need to augment these with an axiom of countable additivity: \(d(\bigcup_{k=0}^{\infty} x_k)  = \sum_{k=0}^{\infty} d(x_k)\) for any pairwise disjoint family \(x_{k}\) of subsets.)  We denote the collection of all distributions on a sample space \(X\) as \(\mathcal{D}(X)\).
In the case of finite sample space, we can define the probabilities of outcomes in terms of singleton sets as \(d_{j} = d(\{j\})\) and these axioms are equivalent to the conditions
+ \(\sum_{j \in S} d_{j} = 1\)
+ \(d(e) = \sum_{j \in e} d(\{j\})\)
** An important property of these axioms is that they are closed under taking convex combinations.  That is to say, if we have \(d, d' \colon E \to [0,1]\) which satisfy the axioms and define \(d'' \colon E \to [0,1]\) as \(d''(e) = s d(e) + (1-s) d'(e)\) for some \(s \in [0,1]\), then \(d''\) also satisfies the axioms.
:PROPERTIES:
:later: 1611780348176
:END:
Since convexity plays an important role in the theory, we will want to restrict attention to maps between distributions which respect convex linear combinations.  One can show that, if \(f \colon \mathcal{D}(X) \to \mathcal{D}(Y)\) is continuous and that 
\[
   f(s d_{1} + (1-s) d_{2}) = s f(d_{1}) + (1-s) f(d_{2}),
\]
then \(f\) is a fractional linear transform, i.e.
\[
  f(d)(\{j\}) = \frac{\sum_{k \in S_{X}} m(j,k) \> d(\{k\})}
    {\sum_{i \in S_{Y}} \sum_{k \in S_{X}} m(i,k) \> d(\{k\})}
\]
for some matrix of non-negative reals \(m \colon S_{Y} \times S_{X} \to [0,\infty)\).  We denote the category of such transforms as \(\mathsf{PStoch}\).  (The first "\(\mathsf{P}\)" stands for "projective" here.)
** The two categories we introduced above are connected by a functor \(\mathcal{D} \colon \mathsf{PProb} \to \mathsf{PStoch}\).  The action on objects assigns to each sample space the collection of distributions as described above.  To each morphism \((D,f) \in \mathsf{PProb}(X,Y)\), we assign the fractional linear transform \(\mathcal{D}(f) \colon \mathcal{D}(X) \to \mathcal{D}(Y)\) which is specified by its action on singletons as
\[ \mathcal{D}(f)(d)(\{j\}) =  \frac{\sum_{k \in D \mid f(k) = j} d(\{k\})}{\sum_{k \in D} d(\{k\})} .\]
** This construct combines several
