#+TITLE: One species example

** To illustrate techniques and concepts, we will write them out for the simple case of a single species reaction system.
:PROPERTIES:
:later: 1611887761901
:END:
\[\begin{aligned}
  \emptyset &\to A \\
  A &\to \emptyset \\
  2A &\to 3A \\
  3A &\to 2A
\end{aligned}\]
*** Recall that, in the ladder operator (Doi-Pelliti) representation, the master equation assumes the form \(\frac{d}{dt} |\rho\rangle = \mathcal{L} |\rho\rangle\) where
:PROPERTIES:
:later: 1611938011441
:END:
\[- \mathcal{L} = \sum\limits_{\mu \to \nu \in R}
                           \frac{k_{\mu \to \nu}}{\prod_{i \in S} \mu_{i}!}
                           \left( \prod_{i \in S} a_{i}^{\dagger \nu_{i}} a_{i}^{\mu_{i}}-
                           \prod_{i \in S} a_{i}^{\dagger \mu_{i}} a_{i}^{\mu_{i}} \right)\]
This may also be expressed in a matrix form as \(-\mathcal{L} = \psi^{T} (a^{\dagger}) \mathbb{A} \psi(a)\) where
\[\begin{aligned}
  \psi(a) &= \begin{pmatrix} 
                      \prod_{i \in S} a_{i}^{c^{1}_i} \\
                      \prod_{i \in S} a_{i}^{c^{2}_i} \\ \vdots
                   \end{pmatrix} \\
  \mathbb{A} &= \begin{pmatrix}
                            0 &
                            \frac{k_{c^{(2)} \to c^{(1)}}}{\prod_{i \in S} c^{(2)}_{i}!} &
                            \cdots \\
                            \frac{k_{c^{(1)} \to c^{(2)}}}{\prod_{i \in S} c^{(1)}_{i}!} &
                            0 & \cdots \\ \vdots & \vdots & \ddots
 \end{pmatrix}
 \end{aligned}\]
In order to write down such a matrix formulaion, we fix an ordering \(c^{(1)}, c^{(2)}, \ldots\) of the complexes appearing as either reactants or products in our set \(R\) of reactions.  When \(c^{(m)} \to c^{(n)} \notin R\), we set \(k_{c^{(m)} \to c^{(n)}} = 0\).
** For our example, we have
:PROPERTIES:
:later: 1611946539401
:END:
\[\begin{aligned} -\mathcal{L} &= k_{\emptyset \to A} (a^{\dagger} - a^{\dagger} a) \\ &+ k_{A \to \emptyset} (a - 1) \\ &+ \frac{1}{2} k_{2A \to 3A} (a^{\dagger 3} a^2 - a^{\dagger 2} a^2) \\ &+ \frac{1}{6} k_{3A \to 2A} (a^{\dagger 2} a^3 - a^{\dagger 3} a^3) \\ \psi(a) &= \begin{pmatrix} 1 \\ a \\ a^2 \\ a^3 \end{pmatrix} \\ \mathbb{A} &= \begin{pmatrix} 0 & k_{A \to \emptyset} & 0 & 0 \\ k_{\emptyset \to A} & 0 & 0 & 0 \\ 0 & 0 & 0 & \frac{1}{6} k_{3A \to 2A} \\ 0 & 0 & \frac{1}{2} k_{2A \to 3A} & 0 \end{pmatrix} \end{aligned} \]
** Next, we bring in the coherent states and obtain the equation of motion for the cumulant generating function.  From the master equation and the definition of the cumulant generating function, we have
\[e^{-\Gamma} \frac{\partial \Gamma}{\partial t} = -\langle 0 | e^{za} \mathcal{L}(a^{\dagger}) | \rho \rangle . \]
We have \(\mathcal{L}\) act to the left.
