#+TITLE: One species example

** To illustrate techniques and concepts, we will write them out for the simple case of a single species reaction system.
:PROPERTIES:
:later: 1611887761901
:END:
\[\begin{aligned}
  \emptyset &\to A \\
  A &\to \emptyset \\
  2A &\to 3A \\
  3A &\to 2A
\end{aligned}\]
** Recall that, in the ladder operator (Doi-Pelliti) representation, the master equation assumes the form \(\frac{d}{dt} |\rho\rangle = \mathcal{L} |\rho\rangle\) where
:PROPERTIES:
:later: 1611938011441
:END:
\[- \mathcal{L} = \sum\limits_{\mu \to \nu \in R}
                           \frac{k_{\mu \to \nu}}{\prod_{i \in S} \mu_{i}!}
                           \left( \prod_{i \in S} a_{i}^{\dagger \nu_{i}} a_{i}^{\mu_{i}}-
                           \prod_{i \in S} a_{i}^{\dagger \mu_{i}} a_{i}^{\mu_{i}} \right)\]
This may also be expressed in a matrix form as \(-\mathcal{L} = \psi^{T} (a^{\dagger}) \mathbb{A} \psi(a)\) where
\[\begin{aligned}
  \psi(a) &= \begin{pmatrix} 
                      \prod_{i \in S} a_{i}^{c^{1}_i} \\
                      \prod_{i \in S} a_{i}^{c^{2}_i} \\ \vdots
                   \end{pmatrix} \\
  \mathbb{A} &= \begin{pmatrix}
                            -\sum_{j} \frac{k_{c^{(1)} \to c^{(j)}}}{\prod_{i \in S} c^{(1)}_{i}!} &
                            \frac{k_{c^{(2)} \to c^{(1)}}}{\prod_{i \in S} c^{(2)}_{i}!} &
                            \cdots \\
                            \frac{k_{c^{(1)} \to c^{(2)}}}{\prod_{i \in S} c^{(1)}_{i}!} &
                            -\sum_{j} \frac{k_{c^{(2)} \to c^{(j)}}}{\prod_{i \in S} c^{(2)}_{i}!}&
                            \cdots \\ \vdots & \vdots & \ddots
 \end{pmatrix}
 \end{aligned}\]
In order to write down such a matrix formulation, we fix an ordering \(c^{(1)}, c^{(2)}, \ldots\) of the complexes appearing as either reactants or products in our set \(R\) of reactions.  When \(c^{(m)} \to c^{(n)} \notin R\), we set \(k_{c^{(m)} \to c^{(n)}} = 0\).
** For our example, we have
:PROPERTIES:
:later: 1611946539401
:END:
\[\begin{aligned} -\mathcal{L} &= k_{\emptyset \to A} (a^{\dagger} - 1) \\ &+ k_{A \to \emptyset} (a - a^{\dagger} a) \\ &+ \frac{1}{2} k_{2A \to 3A} (a^{\dagger 3} a^2 - a^{\dagger 2} a^2) \\ &+ \frac{1}{6} k_{3A \to 2A} (a^{\dagger 2} a^3 - a^{\dagger 3} a^3) \\ \psi &= \begin{pmatrix} 1 \\ a \\ a^2 \\ a^3 \end{pmatrix} \qquad \psi^{\dagger} = \begin{pmatrix} 1 & a^{\dagger} & a^{\dagger 2} & a^{\dagger 3} \end{pmatrix} \\ \mathbb{A} &= \begin{pmatrix} -k_{\emptyset \to A} & k_{A \to \emptyset} & 0 & 0 \\ k_{\emptyset \to A} & -k_{A \to \emptyset} & 0 & 0 \\ 0 & 0 & -\frac{1}{2} k_{2A \to 3A} & \frac{1}{6} k_{3A \to 2A} \\ 0 & 0 & \frac{1}{2} k_{2A \to 3A} & -\frac{1}{6} k_{3A \to 2A} \end{pmatrix} \\ Y &= \begin{pmatrix} 0 & 1 & 2 & 3 \end{pmatrix} \end{aligned} \]
** Next, we bring in the coherent states and obtain the equation of motion for the cumulant generating function.  From the master equation and the definition of the cumulant generating function, we have (cf. eq. 16 in the paper)
\[e^{-\Gamma} \frac{\partial \Gamma}{\partial t} = \langle 0 | e^{za} \mathcal{L}(a^{\dagger}, a) | \rho \rangle . \]
We have \(\mathcal{L}(a^{\dagger}, a)\) act to the left.  Because of the identities
\[\begin{aligned}  \langle 0 | e^{za} a &= \frac{\partial}{\partial z} \langle 0 | e^{za} \\ \langle 0 | e^{za} a^{\dagger} &= z \langle 0 | e^{za} \end{aligned} ,\]
we see that
\[e^{-\Gamma} \frac{\partial \Gamma}{\partial t} = \mathcal{L} (z, \frac{\partial}{\partial z}) \langle 0 | e^{za} | \rho \rangle \]
or, equivalently,
\[\frac{\partial \Gamma}{\partial t} = e^{\Gamma} \mathcal{L} (z, \frac{\partial}{\partial z}) e^{-\Gamma} .\]
This is the desired differential equation for \(\Gamma\).  For our example system, it works out to be
\[\frac{\partial \Gamma}{\partial t} = -k_{\emptyset \to A} (z - 1)  - k_{A \to \emptyset} (1 - z) e^{\Gamma} \frac{\partial}{\partial z} e^{-\Gamma} - \frac{1}{2} k_{2A \to 3A} (z^{3} - z^{2}) e^{\Gamma} \frac{\partial^2}{\partial z^2} e^{-\Gamma} - \frac{1}{6} k_{3A \to 2A} (z^{2} - z^{3}) e^{\Gamma} \frac{\partial^3}{\partial z^3} e^{-\Gamma} \]
** To see what the solution looks like in a simple example, suppose that \(k_{2A \to 3A} = k_{3A \to 2A} = 0\) ("ID" process).  Then we may write the equation as
:PROPERTIES:
:later: 1613159768588
:END:
\[\frac{\partial \Gamma}{\partial t} - k_{A \to \emptyset} (1 - z) \frac{\partial \Gamma}{\partial z} = -k_{\emptyset \to A} (z - 1) .\]
Since this equation is linear, its solution will be the sum of a particular solution of the inhomogeneous equation and the general solution of the homogeneous equation.   As the particular solution we will take the time-independant solution \(\Gamma = \frac{k_{\emptyset \to A}}{k_{A \to \emptyset}} z\).  Since the homogenous equation,
\[\frac{\partial \Gamma}{\partial t} - k_{A \to \emptyset} (1 - z) \frac{\partial \Gamma}{\partial z} =0,\]
is of first order, a function of \(z\) and \(t\) will be a solution iff it is constant along characteristics.  These are determined by the equation
\[\frac{dz}{dt} = - k_{A \to \emptyset} (1 - z)\]
as \(z = 1 + C e^{k_{A \to \emptyset} t}\).  Thus we have the general solution
\[ \Gamma = f(e^{-k_{A \to \emptyset} t} (z - 1)) + \frac{k_{\emptyset \to A}}{k_{A \to \emptyset}} z. \]
This may be re-expressed in terms of initial data as
\[\Gamma = \Gamma_{0} (e^{-k_{A \to \emptyset} t} (z - 1) + 1) + \frac{k_{\emptyset \to A}}{k_{A \to \emptyset}} (1 - e^{-k_{A \to \emptyset} t}) (z - 1)\]
Making the change of variable, this becomes
\[\Gamma = \Gamma_{0} (e^{-k_{A \to \emptyset} t} (e^{\theta} - 1) - 1) + \frac{k_{\emptyset \to A}}{k_{A \to \emptyset}} (1 - e^{-k_{A \to \emptyset} t}) (e^{\theta} + 1)\]
\[\Gamma (\theta, t) = f(e^{-k_{A \to \emptyset} t} (e^{\theta} - 1)) + \frac{k_{\emptyset \to A}}{k_{A \to \emptyset}} e^{\theta} .\]
For concreteness, let us pick the initial condition of a single \(A\) at time zero, i.e. \(\Gamma_{0} (\theta) = -\theta\). 
\[ \Gamma (\theta, t) = \frac{k_{\emptyset \to A}}{k_{A \to \emptyset}} \left(  e^{-k_{A \to \emptyset} t} (e^{\theta} - 1)  + 1 - e^{\theta} \right) + \log (e^{-k_{A \to \emptyset} t} (e^{\theta} - 1) + 1) \]
** To obtain the large deviation limit, we first make an eikonal approximation.  This consists in retaining only the first derivative terms in the derivative of the exponential:
\[ \frac{\partial^k}{\partial z^k} e^{-\Gamma} \approx e^{-\Gamma} \left( - \frac{\partial \Gamma}{\partial z} \right)^k\]
But applying the identites to the expression for average number,
\[n = \frac{\langle 0 | e^{za} a{\dagger} a | \rho \rangle}{\langle 0 | e^{za} | \rho \rangle} = \frac{z \partial(\langle 0 | e^{za} | \rho \rangle) / \partial z}{\langle 0 | e^{za} | \rho \rangle} ;\]
by definition of \(\Gamma\) as a generating function, we obtain
\[-\frac{\partial \Gamma}{\partial z} = \frac{n}{z} .\]
Hence, our eikonal approximation may be expressed as
\[ \frac{\partial^k}{\partial z^k} e^{-\Gamma} \approx e^{-\Gamma} \left( \frac{n}{z} \right)^k ,\]
so the approximation to the equation of motion (eq. 17 in the paper) is
\[\frac{\partial \Gamma^{\mathrm{class}}}{\partial t} = \mathcal{L}^{\mathrm{class}} (z, n/z) .\]
In the example, this assumes the form
\[\frac{\partial \Gamma^{\mathrm{class}}}{\partial t} = k_{\emptyset \to A} (z - 1)  + k_{A \to \emptyset} (1 - z) \frac{n}{z} + \frac{1}{2} k_{2A \to 3A} (z^{3} - z^{2}) \left( \frac{n}{z} \right)^{2} + \frac{1}{6} k_{3A \to 2A} (z^{2} - z^{3}) \left( \frac{n}{z} \right)^{3}  = (k_{\emptyset \to A} + \frac{1}{2} k_{2A \to 3A} n^{2}) (z - 1) + (k_{A \to \emptyset} + \frac{1}{6} k_{3A \to 2A} n^{3}) (\frac{1}{z} - 1)\]
or, changing variable,
\[\frac{\partial \Gamma^{\mathrm{class}}}{\partial t} = (k_{\emptyset \to A} + \frac{1}{2} k_{2A \to 3A} n^{2}) (e^{\theta} - 1) + (k_{A \to \emptyset} n + \frac{1}{6} k_{3A \to 2A} n^{3}) (e^{-\theta} - 1)\]
** So now we can write down the Hamiltonian equations (23, 24 in the paper):
\[\begin{aligned} \frac{\partial \theta}{\partial t} &= \frac{\partial \mathcal{L}}{\partial n} =  k_{2A \to 3A} n (e^{\theta} - 1) + (k_{A \to \emptyset} + \frac{1}{2} k_{3A \to 2A} n^2) (e^{-\theta} - 1) \\ \frac{\partial n}{\partial t} &= -\frac{\partial \mathcal{L}}{\partial \theta} =  (k_{\emptyset \to A} + \frac{1}{2} k_{2A \to 3A} n^{2}) e^{\theta} + (k_{A \to \emptyset} n - \frac{1}{6} k_{3A \to 2A} n^{3}) e^{-\theta} \end{aligned}\]
Note that when \(\theta = 0\), the first equation is satisfied and the second equation reduces to the rate equation.  Because \(\mathcal{L}^{\mathrm{class}}\) does not depend on \(t\) explicitly, it's value is conserved under motion.  Call this constant value \(\ell\).  Then we may solve for \(\theta\) in terms of \(\ell\) and \(n\).  In the special case of \(\ell = 0\), this simplifies to
\[e^{\theta} = \frac{k_{3A \to 2A} n^3 + 6 k_{A \to \emptyset} n}{2 k_{2A \to 3A} n^2 + 6 k_{\emptyset \to A}}.\]
Substituting this into the Hamiltonian equation, we obtain the equation
\[\frac{\partial n}{\partial t} = \frac{3 k_{2A \to 3A} k_{3A \to 2A} n^5 + 6 k_{\emptyset \to A} k_{3A \to 2A} n^3 + 18 k_{A \to \emptyset} k_{2A \to 3A} n^3 + 36 k_{\emptyset \to A} k_{A \to \emptyset} n - 1}{18 k_{2A \to 3A} n^2 + 36 k_{\emptyset \to A}} \]
**
